"""empty message

Revision ID: 05d71018cefd
Revises: 33e4e184c429
Create Date: 2025-03-23 19:12:58.303989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d71018cefd'
down_revision = '33e4e184c429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbs_up', sa.Integer(), nullable=True, comment='点赞'))
        batch_op.add_column(sa.Column('collect', sa.Integer(), nullable=True, comment='收藏'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('collect')
        batch_op.drop_column('thumbs_up')

    # ### end Alembic commands ###
