"""empty message

Revision ID: 33e4e184c429
Revises: 
Create Date: 2025-03-21 16:29:00.160233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e4e184c429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='邮箱'),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='密码（密文）'),
    sa.Column('gender', sa.String(length=2), nullable=True, comment='性别'),
    sa.Column('birth_day', sa.String(length=30), nullable=True, comment='生日'),
    sa.Column('career', sa.String(length=30), nullable=True, comment='职业'),
    sa.Column('created_at', sa.String(length=30), nullable=True, comment='注册时间'),
    sa.Column('avatar', sa.String(length=150), nullable=True, comment='头像'),
    sa.Column('real_name', sa.String(length=20), nullable=True, comment='实名'),
    sa.Column('id_card', sa.String(length=25), nullable=True, comment='身份证'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_gender'), ['gender'], unique=False)

    op.create_table('action',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False, comment='行为ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=30), nullable=True, comment='详细信息'),
    sa.Column('type', sa.String(length=10), nullable=True, comment='类别'),
    sa.Column('description', sa.String(length=50), nullable=True, comment='详细信息'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False, comment='文章ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False, comment='摘要'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('created_at', sa.String(length=30), nullable=True, comment='启动时间'),
    sa.Column('show_image', sa.String(length=150), nullable=True, comment='展示图片'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False, comment='项目ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('created_at', sa.String(length=30), nullable=True, comment='注册时间'),
    sa.Column('scenario', sa.String(length=20), nullable=False, comment='项目场景'),
    sa.Column('scale', sa.String(length=5), nullable=False, comment='项目场景'),
    sa.Column('detection_classes', sa.JSON(), nullable=False, comment='检测类别列表'),
    sa.Column('conf_threshold', sa.Float(), nullable=True, comment='置信度阈值'),
    sa.Column('source_path', sa.String(length=200), nullable=False, comment='源文件路径'),
    sa.Column('result_path', sa.String(length=200), nullable=True, comment='结果文件路径'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False, comment='评论ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('likes', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('created_at', sa.String(length=30), nullable=True, comment='发布时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('detection_data',
    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False, comment='数据ID'),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False, comment='检测结果'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_data')
    op.drop_table('comment')
    op.drop_table('project')
    op.drop_table('article')
    op.drop_table('action')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_gender'))

    op.drop_table('user')
    # ### end Alembic commands ###
